const dummyData = [
    {   
        id: 0,
        name: '[홀리차우] 스위트앤사워포크',
        image:'https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1657617005703l0.jpg',
        discountRate: '25%',
        salesPrice: '4,950원',
        dimmedPrice: '12,900원',
        delivery: '샛별배송',
        description: '매콤달콤한 매력의 밥도둑',

        only: true,            
    },
    {   
        id: 1,
        name: '[자연에찬] 강화순열무 나박김치',
        image:'https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1653034669549l0.jpeg',
        // discountRate: '25%',
        salesPrice: '4,950원',
        // dimmedPrice: '12,900원',
        delivery: '샛별배송',
        only: false, 
        description: '매콤달콤한 매력의 밥도둑',
    },
    {   
        id: 2,
        name: '[홀리차우] 스위트앤사워포크',
        image:'https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1653040305679l0.jpg',
        discountRate: '25%',
        salesPrice: '4,950원',
        dimmedPrice: '12,900원',
        only: true, 
        description: '매콤달콤한 매력의 밥도둑',
    },
    {   
        id: 3,
        name: '[홀리차우] 스위트앤사워포크',
        image:'https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1576637818415l0.jpg',
        discountRate: '25%',
        salesPrice: '4,950원',
        dimmedPrice: '12,900원',
        only: true, 
        description: '매콤달콤한 매력의 밥도둑',
    },
    {   
        id: 4,
        name: '[홀리차우] 스위트앤사워포크',
        image:'https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1657617005703l0.jpg',
        discountRate: '25%',
        salesPrice: '4,950원',
        dimmedPrice: '12,900원',
        delivery: '샛별배송',
        description: '매콤달콤한 매력의 밥도둑',

        only: true,            
    },
    {   
        id: 5,
        name: '[자연에찬] 강화순열무 나박김치',
        image:'https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1653034669549l0.jpeg',
        // discountRate: '25%',
        salesPrice: '4,950원',
        // dimmedPrice: '12,900원',
        delivery: '샛별배송',
        only: true, 
        description: '매콤달콤한 매력의 밥도둑',
    },
    {   
        id: 6,
        name: '[홀리차우] 스위트앤사워포크',
        image:'https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1653040305679l0.jpg',
        discountRate: '25%',
        salesPrice: '4,950원',
        dimmedPrice: '12,900원',
        only: true, 
        description: '매콤달콤한 매력의 밥도둑',
    },
    {   
        id: 7,
        name: '[홀리차우] 스위트앤사워포크',
        image:'https://img-cf.kurly.com/cdn-cgi/image/width=400,format=auto/shop/data/goods/1576637818415l0.jpg',
        discountRate: '25%',
        salesPrice: '4,950원',
        dimmedPrice: '12,900원',
        only: true, 
        description: '매콤달콤한 매력의 밥도둑',
    },
]
export default dummyData;